name: ProdiusTerm
options:
  bundleIdPrefix: com.prodiusterm
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift.git
    from: "7.4.1"
  SwiftTerm:
    url: https://github.com/migueldeicaza/SwiftTerm.git
    from: "1.2.7"

targets:
  ProdiusTerm:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - Sources
    info:
      path: Info.plist
    entitlements:
      path: ProdiusTerm.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.prodiusterm.desktop
        PRODUCT_NAME: ProdiusTerm
        MARKETING_VERSION: "0.1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "6.0"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.developer-tools
        CODE_SIGN_ENTITLEMENTS: ProdiusTerm.entitlements
    dependencies:
      - package: GRDB
        product: GRDB
      - package: SwiftTerm
        product: SwiftTerm
